function [SubjectID, Age, Gender, Weight, Day1, Day2, Day3] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ISOK_DATA_6803 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ISOK_DATA_6803 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  isok_data_6803 = importfile("C:\Users\CAPie\OneDrive\Documents\GitHub\CAP_KINE6203_Assignment_Solutions\assignment4\isok_data_6803.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2025 12:47:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SubjectID", "Age", "Gender", "Weight", "Day1", "Day2", "Day3"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Gender", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "SubjectID", "TrimNonNumeric", true);
opts = setvaropts(opts, "SubjectID", "ThousandsSeparator", ",");

% Import the data
isok_data_6803 = readtable(filename, opts);

SubjectID=data(:,1);
Age=data(:,2);
Gender=data(:,3);
Weight=data(:,4);
Day1=data(:,5);
Day2=data(:,6);
Day3=data(:,7);

end